name: Capture Snapshots and Upload

on:
  schedule:
    - cron: '*/5 * * * *'  # Every 5 minutes
  workflow_dispatch:

jobs:
  snapshot:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install yt-dlp
        run: python -m pip install -U yt-dlp

      - name: Install ffmpeg
        uses: FedericoCarboni/setup-ffmpeg@v2

      - name: Capture snapshots
        run: |
          TIMESTAMP=$(date +'%H%M')
          DATE=$(date +'%m-%d')
          mkdir -p YT_Poland/$DATE YT_Mechelen1/$DATE YT_Mechelen2/$DATE YT_Lokeren/$DATE
          yt-dlp -f best -o "YT_Poland/$DATE/${TIMESTAMP}.mp4" https://www.youtube.com/watch?v=S2L-hzuRX0g --download-sections "*00:00-00:01"
          yt-dlp -f best -o "YT_Mechelen1/$DATE/${TIMESTAMP}.mp4" https://www.youtube.com/watch?v=xQKCnSsATK0 --download-sections "*00:00-00:01"
          yt-dlp -f best -o "YT_Mechelen2/$DATE/${TIMESTAMP}.mp4" https://www.youtube.com/watch?v=m5HWzP2wNGE --download-sections "*00:00-00:01"
          yt-dlp -f best -o "YT_Lokeren/$DATE/${TIMESTAMP}.mp4" https://www.youtube.com/watch?v=HUeaYuBLNNQ --download-sections "*00:00-00:01"

      - name: Save rclone config to file
        run: |
          echo '${{ secrets.RCLONE_CONFIG }}' > gdrive.json

      - name: Install rclone
        run: |
          curl https://rclone.org/install.sh | sudo bash

      - name: Configure rclone
        run: |
          echo "[gdrive]" > rclone.conf
          echo "type = drive" >> rclone.conf
          echo "scope = drive" >> rclone.conf
          echo "service_account_file = $(pwd)/gdrive.json" >> rclone.conf

      - name: Upload to Google Drive
        run: |
          rclone --config rclone.conf copy YT_Poland gdrive:YT_Snapshots/YT_Poland
          rclone --config rclone.conf copy YT_Mechelen1 gdrive:YT_Snapshots/YT_Mechelen1
          rclone --config rclone.conf copy YT_Mechelen2 gdrive:YT_Snapshots/YT_Mechelen2
          rclone --config rclone.conf copy YT_Lokeren gdrive:YT_Snapshots/YT_Lokeren

      - name: Clean up repo and push
        run: |
          rm -rf YT_*
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add -u
          git commit -m "Cleanup snapshots $(date)"
          git push || echo "Nothing to commit"
