name: Capture Livestream Snapshots

on:
  schedule:
    - cron: "*/5 * * * *"  # Every 5 minutes
  workflow_dispatch:

jobs:
  snapshot:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install yt-dlp and ffmpeg
        run: |
          sudo apt update
          sudo apt install -y ffmpeg
          pip install -U yt-dlp

      - name: Save cookies to file
        run: echo "${{ secrets.YT_COOKIES }}" > cookies.txt

      - name: Capture snapshots
        run: |
          declare -A STREAMS
          STREAMS["YT_Poland"]="https://www.youtube.com/watch?v=S2L-hzuRX0g"
          STREAMS["YT_Mechelen1"]="https://www.youtube.com/watch?v=xQKCnSsATK0"
          STREAMS["YT_Mechelen2"]="https://www.youtube.com/watch?v=m5HWzP2wNGE"
          STREAMS["YT_Lokeren"]="https://www.youtube.com/watch?v=HUeaYuBLNNQ"

          DATE=$(date +'%m-%d')
          TIME=$(date +'%H%M')

          for NAME in "${!STREAMS[@]}"; do
            mkdir -p "$NAME/$DATE"
            yt-dlp --cookies cookies.txt --no-warnings --quiet --skip-download \
              --write-thumbnail --convert-thumbnails jpg \
              -o "$NAME/$DATE/$TIME.%(ext)s" "${STREAMS[$NAME]}"
          done

      - name: Commit and push snapshots
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add YT_*/
          git commit -m "Add snapshots for $(date +'%m-%d %H:%M')" || echo "Nothing to commit"
          git push
