name: Capture Livestream Snapshots

on:
  schedule:
    - cron: "*/5 * * * *"  # Every 5 minutes
  workflow_dispatch:       # Allows manual triggering

jobs:
  snapshot:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install yt-dlp and ffmpeg
        run: |
          sudo apt update
          sudo apt install -y ffmpeg
          pip install -U yt-dlp

      - name: Save cookies to file
        run: echo "${{ secrets.YT_COOKIES }}" > cookies.txt

      - name: Capture snapshots
        run: |
          mkdir -p snapshots
          TIMESTAMP=$(date +'%m-%d-%H%M')
          mkdir -p snapshots/$TIMESTAMP

          STREAMS=(
            "https://www.youtube.com/watch?v=S2L-hzuRX0g"
            "https://www.youtube.com/watch?v=xQKCnSsATK0"
            "https://www.youtube.com/watch?v=m5HWzP2wNGE"
            "https://www.youtube.com/watch?v=HUeaYuBLNNQ"
          )

          for i in "${!STREAMS[@]}"; do
            yt-dlp --cookies cookies.txt --no-warnings --quiet --skip-download \
              --write-thumbnail --convert-thumbnails jpg \
              -o "snapshots/$TIMESTAMP/cam_$i.%(ext)s" "${STREAMS[$i]}"
          done

      - name: Commit and push snapshots
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add snapshots/
          git commit -m "Add snapshots for $TIMESTAMP" || echo "Nothing to commit"
          git push
