name: Capture Snapshots

on:
  schedule:
    - cron: '*/5 * * * *'
  workflow_dispatch:

jobs:
  capture:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install yt_dlp
        run: pip install yt-dlp

      - name: Capture snapshots
        run: |
          mkdir -p snapshots
          TIMESTAMP=$(date +'%m-%d-%H%M')
          mkdir -p snapshots/$TIMESTAMP

          # List of YouTube livestreams
          STREAMS=(
            "https://www.youtube.com/watch?v=S2L-hzuRX0g"
            "https://www.youtube.com/watch?v=xQKCnSsATK0"
            "https://www.youtube.com/watch?v=m5HWzP2wNGE"
            "https://www.youtube.com/watch?v=HUeaYuBLNNQ"
          )

          for i in "${!STREAMS[@]}"; do
            yt-dlp --no-warnings --quiet --skip-download \
              --write-thumbnail --convert-thumbnails jpg \
              -o "snapshots/$TIMESTAMP/cam_$i.%(ext)s" "${STREAMS[$i]}"
          done

      - name: Commit and push
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

          git add snapshots/
          git commit -m "Add snapshots for $(date +'%m-%d-%H%M')" || echo "No changes to commit"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
